### ISSUE TITLE
NickServ

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/clean-irc#2]
It would be nice if clooglebot could work with NickServ to safeguard its nick.

**Comment by dopefishh** [comment]
Can be done, just register the nickname and add the registration commands to the startup command [here](https://github.com/clean-cloogle/clean-irc/blob/master/cloogle.icl#L167).

**Comment by camilstaps** [comment]
I'm just unsure what should be done if somebody else is currently using the nick, but yes, it can be done surely.

**Comment by dopefishh** [comment]
If someone else uses the nick they get a force change or a kick. The only problem is, how to store the password. Obviously it can't be stored in the repo. Maybe we can add it as a command line parameter to the cloogle bot.

**Comment by camilstaps** [comment]
The problem is you can't login if the nick is in use (?)

We could also use a ini or dotenv file with settings, also for the nick and initial channels.

**Comment by dopefishh** [comment]
That is not a problem. Only people with the correct password can login. If someone uses the reserved nickname, they will have to identify within 30 seconds or they will be kicked.
